export const CREATE_PARCEL = "CREATE_PARCEL"
export const GET_USER_PARCEL = "GET_USER_PARCEL"
export const CANCEL_USER_PARCEL = "CANCEL_USER_PARCEL"
export const CHANGE_USER_PARCEL_DESTINATION = "CHANGE_USER_PARCEL_DESTINATION"

// success
export const CANCEL_USER_PARCEL_SUCCESS = "CANCEL_USER_PARCEL_SUCCESS"
export const CHANGE_USER_PARCEL_DESTINATION_SUCCESS = "CHANGE_USER_PARCEL_DESTINATION_SUCCESS"
export const GET_PARCEL_SUCCESS = "GET_PARCEL_SUCCESS"
export const CREATE_PARCEL_SUCCESS = "CREATE_PARCEL_SUCCESS"

// user
export const USER_LOGIN = "USER_LOGIN"
export const USER_SIGNUP = "USER_SIGNUP"
export const USER_LOGOUT = "USER_LOGOUT"

// success types
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"

// failed types
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED"
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED"